Use git-squash and git-tupdate

diff --git a/git-ship b/git-ship
--- a/git-ship
+++ b/git-ship
@@ -15,17 +15,8 @@ then
 	die "You can not ship from master"
 fi
 
-echo "$(tput setaf 6)Checking out master and getting latest...$(tput sgr0)"
-git checkout master
-git tf pull --rebase || { die "Pulling latest TFS changes into master failed" }
-git checkout ${currentBranch}
-git rebase master || { die "Rebasing ${currentBranch} failed" }
-git checkout master
-
-echo "$(tput setaf 6)Merging ${currentBranch} into master...$(tput sgr0)"
-git merge --squash ${currentBranch} || { die "Merging ${currentBranch} into master failed" }
-git add -A || { die "Staging merged changes into master failed" }
-git commit -m "$1" || { die "Committing merged changes into master failed" }
+git tupdate || { die "Updating from TFS failed" }
+git squash || { die "Squash-merging into master failed" }
 
 if [ -z "$2" ]
 then
@@ -35,6 +26,3 @@ else
 	echo "$(tput setaf 6)Checking in ${currentBranch} to TFS and associating to #$2...$(tput sgr0)"
 	git tf checkin -m "$1" --associate=$2 || { die "Checking in ${currentBranch} to TFS failed" }
 fi
-
-echo "$(tput setaf 6)Deleting branch ${currentBranch}...$(tput sgr0)"
-git branch -D ${currentBranch} || { die "Deleting branch ${currentBranch} failed" }
