In git-squash changed source to dot (.) and removed some quotes

diff --git a/git-squash b/git-squash
--- a/git-squash
+++ b/git-squash
@@ -1,7 +1,9 @@
 #!/bin/sh
 # ship: Ship current branch to development branch
 
-source "$(git --exec-path)/git-sh-setup"
+. "$(git --exec-path)/git-sh-setup"
+
+echo "$(tput setaf 6)Squash committing ${currentBranch} into master...$(tput sgr0)"
 
 if [ -z "$1" ]
 then
@@ -15,11 +17,10 @@ then
 	die "You can not ship from master"
 fi
 
-echo "$(tput setaf 6)Merging ${currentBranch} into master...$(tput sgr0)"
 git checkout master
-git merge --squash ${currentBranch} || { die "Merging ${currentBranch} into master failed" }
-git add -A || { die "Staging merged changes into master failed" }
-git commit -m "$1" || { die "Committing merged changes into master failed" }
+git merge --squash "${currentBranch}" || { die "Merging ${currentBranch} into master failed"; }
+git add -A || { die "Staging merged changes into master failed"; }
+git commit -m "$1" || { die "Committing merged changes into master failed"; }
 
 echo "$(tput setaf 6)Deleting branch ${currentBranch}...$(tput sgr0)"
-git branch -D ${currentBranch} || { die "Deleting branch ${currentBranch} failed" }
+git branch -D "${currentBranch}" || { die "Deleting branch ${currentBranch} failed"; }
